---

{% set validate_testcase = validate_testcase or '' %}
{% set testcase = testcase or '' %}
{% set dovetail_home = dovetail_home or '' %}
{% set debug = debug or 'false' %}
{% set build_tag = build_tag or '' %}
{% set openrc_file = '/home/opnfv/functest/conf/env_file' %}
{% set kube_file = '/root/.kube/config' %}
{% set result_dir = '/home/opnfv/functest/results' %}

functest-k8s:
  image_name: opnfv/functest-kubernetes-healthcheck
  docker_tag: gambia
  opts:
    detach: true
    stdin_open: true
  shell: '/bin/bash'
  envs:
    - 'INSTALLER_TYPE=unknown'
    - 'DEPLOY_SCENARIO=k8-deploy'
    - 'NODE_NAME=unknown'
    - 'TEST_DB_URL=file:///home/opnfv/functest/results/functest_results.txt'
    - 'CI_DEBUG={{debug}}'
    - 'BUILD_TAG={{build_tag}}-{{testcase}}'
  volumes:
    - '{{dovetail_home}}/pre_config/k8.creds:{{openrc_file}}'
    - '{{dovetail_home}}/pre_config/admin.conf:{{kube_file}}'
    - '{{dovetail_home}}/results/:{{result_dir}}'
  pre_condition:
    - 'echo test for precondition in functest'
  cmds:
    - 'run_tests -t {{validate_testcase}} -r'
  post_condition:
    - 'echo test for postcondition in functest'
  openrc: {{openrc_file}}
