#######################################################
# All rights reserved. This program and the accompanying materials
# are made available under the terms of the Apache License, Version 2.0
# which accompanies this distribution, and is available at
# http://www.apache.org/licenses/LICENSE-2.0
#

FROM ubuntu:16.04
MAINTAINER Leo Wang <grakiss.wanglei@huawei.com>
LABEL version="v1" description="CVP nginx"


ENV HOME /home
WORKDIR /home

RUN apt-get update

RUN apt-get install -y git nginx supervisor

RUN git clone http://github.com/grakiss888/testapi

RUN mkdir /www
RUN cp -r /home/testapi/3rd_party/static /www/


ADD nginx/nginx.conf /etc/nginx/nginx.conf
ADD nginx/sites-enabled/default /etc/nginx/sites-available/default
ADD nginx/sites-enabled/default /etc/nginx/sites-enabled/default
ADD supervisor/conf.d/nginx.conf /etc/supervisor/conf.d/nginx.conf
ADD start-nginx.sh /home/start-nginx.sh

CMD ["bash", "start-nginx.sh"]
